config/routes.rb
Rails.application.routes.draw do
  resources :searches

  devise_for :users

  root 'home#index'

end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :searches

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		render :index
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:name, :splunkquery, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-default" role="navigation">

	<%= link_to(image_tag("screens_applogo-grey.png", :class => "headerLogo", :alt => "logo", :size => "20", :title => 'gQuery')) %>

	<!--	
	<ul class="nav navbar-nav">
		<li class="createQuery">
			<a href="#">Query</a>
		</li>
		<li>
			<a href="#">Home</a>
		</li>
		<li>
			<a href="#">Link</a>
		</li>
		
		<li class="sign-in">
			<a href="#">Sign in</a>
		</li>
		<li class="register">
			<a href="#">Register</a>
		</li>
	</ul>
	-->
</nav>
	
<div class="fullwidth-container">
	<div class="row">
		<aside class="span5" id="queryBar"><!-- Sidebar starts here  -->    
          	<div class="filterValues">
	            <form>
	    			<div class="form-group">
	        			<label for="searchName" class="SearchLabel">Search name:</label>
	  					<br><br>
	    			</div>
	        		<div id="sliderContainer"> 
						<p>
						  <%= link_to(image_tag("screens_crime.png", :class => "crimeRate", :alt => "crimeRate", :size => "20", :title => 'crimeRate')) %>
						  <label for="crimeRateValue" class="indicatorLabel"> Crime Rate:</label>
						  <input type="text" id="crimeRateValue" class="indicatorValue" readonly > </input>
						</p>
		 
						<div id="slider-range-crime"></div>
						<p>
						  <%= link_to(image_tag("screens_pollution.png", :class => "pollutionRate", :alt => "pollutionRate", :size => "20", :title => 'pollutionRate')) %>
						  <label for="pollutionRateValue" class="indicatorLabel"> Pollution Rate:</label>
						  <input type="text" id="pollutionRateValue" class="indicatorValue" readonly > </input>
						</p>
		 
						<div id="slider-range-pollution"></div>
						<p>
						  <%= link_to(image_tag("screens_health.png", :class => "healthRate", :alt => "healthRate", :size => "20", :title => 'healthRate')) %>
						  <label for="healthRateValue" class="indicatorLabel"> Pollution Rate:</label>
						  <input type="text" id="healthRateValue" class="indicatorValue" readonly > </input>
						</p>
						<div id="slider-range-health"></div>

						<p>
						  <%= link_to(image_tag("screens_health.png", :class => "healthRate", :alt => "healthRate", :size => "20", :title => 'healthRate')) %>
						  <label for="urbannessRateValue" class="indicatorLabel"> Urbanization Rate:</label>
						  <input type="text" id="urbannessRateValue" class="indicatorValue" readonly > </input>
						</p>
						<div id="slider-range-urbanness"></div>

						<p>
						  <%= link_to(image_tag("screens_health.png", :class => "healthRate", :alt => "healthRate", :size => "20", :title => 'healthRate')) %>
						  <label for="greennessRateValue" class="indicatorLabel"> Green Cover:</label>
						  <input type="text" id="greennessRateValue" class="indicatorValue" readonly > </input>
						</p>
						<div id="slider-range-greenness"></div>
					</div>
	    			<br><br>
	    			<div id="adjustFilters" class="dropdown">
		    			<button class="searchButton btn btn-primary" onclick="splunkSearch()">Search</button>
		    			<button id="addFilter" type="button" data-toggle="dropdown" class="dropdown-toggle addFilter btn btn-primary" >+
		    				<span class="caret"></span>
		    				</button>
		     		   <ul class="dropdown-menu" id="dropdownList" aria-labelledby="dropdownMenu1">
				            <li id="Health-Pollution" onclick="selectCategory(id)">Health/ Pollution</li>
				            <li id="Safety-Crime" onclick="selectCategory(id)">Safety/ Crime</li>
				            <li id="Economy" onclick="selectCategory(id)">Economic Factors</li>
				            <li id="Infrastructure" onclick="selectCategory(id)">Infrastructure</li>
				            <li class="divider"></li>
				            <li id="GeneralHealthIndicator" onclick="selectCategory(id)">OverallHealth</li>
					    </ul>
					</div>
				</form>
           </div>
        </aside>
    </div>


	<div class="col-12" style="position: fixed; z-index: 100;">
	    <div id="map" class="map"></div>
	</div>
	<div style="display: block; box-sizing: border-box; height: 301px;">
	</div>

	<div class="chartcontainer">
		<div>
			<div class="panelheader-div">
			<span class="column-left"> <%= link_to(image_tag("screens_pollution.png", :class => "pollutionRate", :alt => "pollutionRate", :size => "48", :title => 'pollutionRate')) %></span>
			<span class="column-center"><h2 style="height:48px">Pollution</h2></span>
			<span class="column-right"> <%= link_to(image_tag("loadingindicator.gif", :class => "pollutionchartloading", :alt => "loadingindicator", :size => "32", :title => 'loadingindicator')) %></span>
			</div>
			<div id="pollutionchart">
			</div>
		</div>
		<div>
			<div class="panelheader-div">
			<span class="column-left"> <%= link_to(image_tag("screens_crime.png", :class => "crimeRate", :alt => "crimeRate", :size => "48", :title => 'crimeRate')) %></span>
			<span class="column-center"><h2 style="height:48px">Crime</h2></span>
			<span class="column-right"> <%= link_to(image_tag("loadingindicator.gif", :class => "crimechartloading", :alt => "loadingindicator", :size => "32", :title => 'loadingindicator')) %></span>
			</div>
			<div id="crimechart"></div>
		</div>
		<div>
			<div class="panelheader-div">
			<span class="column-left"> <%= link_to(image_tag("screens_health.png", :class => "healthRate", :alt => "healthRate", :size => "48", :title => 'healthRate')) %></span>
			<span class="column-center"><h2 style="height:48px">Health</h2></span>
			<span class="column-right"> <%= link_to(image_tag("loadingindicator.gif", :class => "healthchartloading", :alt => "loadingindicator", :size => "32", :title => 'loadingindicator')) %></span>
			</div>
			<div id="healthchart"></div>
		</div>
		<div>
			<div class="panelheader-div">
			<span class="column-left"> <%= link_to(image_tag("screens_greenness.png", :class => "greennessRate", :alt => "greennessRate", :size => "48", :title => 'healthRate')) %></span>
			<span class="column-center"><h2 style="height:48px">Greenness</h2></span>
			<span class="column-right"> <%= link_to(image_tag("loadingindicator.gif", :class => "greenchartloading", :alt => "loadingindicator", :size => "32", :title => 'loadingindicator')) %></span>
			</div>
			<div id="greenchart"></div>
		</div>
		<div>
			<div class="panelheader-div">
			<span class="column-left"> <%= link_to(image_tag("screens_greenness.png", :class => "urbannessRate", :alt => "urbannessRate", :size => "48", :title => 'healthRate')) %></span>
			<span class="column-center"><h2 style="height:48px">Urbanness</h2></span>
			<span class="column-right"> <%= link_to(image_tag("loadingindicator.gif", :class => "urbanchartloading", :alt => "loadingindicator", :size => "32", :title => 'loadingindicator')) %></span>
			</div>
			<div id="urbanchart"></div>
		</div>

		<div>
		<div id="twittertagcloud" style="width:100%; height:400px">
		</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gQuery</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches-bak/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :splunkquery %><br>
    <%= f.text_field :splunkquery %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches-bak/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches-bak/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Searches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Splunkquery</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.name %></td>
        <td><%= search.splunkquery %></td>
        <td><%= search.user_id %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches-bak/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches-bak/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @search.name %>
</p>

<p>
  <strong>Splunkquery:</strong>
  <%= @search.splunkquery %>
</p>

<p>
  <strong>User:</strong>
  <%= @search.user_id %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/searches/_form.html.erb
<%= form_for @search, :html => { :class => "form-horizontal search" } do |f| %>

  <% if @search.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @search.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :splunkquery, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :splunkquery, :class => 'form-control' %>
    </div>
    <%=f.error_span(:splunkquery) %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                searches_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/searches/edit.html.erb
<%- model_class = Search -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/searches/index.html.erb
<%- model_class = Search -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>

      <th><%= model_class.human_attribute_name(:name) %></th>

      <th><%= model_class.human_attribute_name(:splunkquery) %></th>

      <th><%= model_class.human_attribute_name(:user_id) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= link_to search.id, search_path(search) %></td>

        <td><%= search.name %></td>

        <td><%= search.splunkquery %></td>

        <td><%= search.user_id %></td>

        <td><%=l search.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_search_path(search), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      search_path(search),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_search_path,
            :class => 'btn btn-primary' %>

app/views/searches/new.html.erb
<%- model_class = Search -%>
	    <script type="text/javascript" charset="utf-8">

            $(document).ready(function (){
                var http = new splunkjs.ProxyHttp("/proxy");
                var service = new splunkjs.Service(http, {
                    username: "admin",
                    password: "admin",
                });
                service.login(function(err, success) {
                    if (err) {
                        throw err;
                    }
                    console.log("Login was successful: " + success);
                    service.jobs().create('search index=_internal | head 1000 | stats count(host), count(source) by sourcetype',{
                        status_buckets: 300
                    }, function(err, job){
                        if(err){
                            console.log(err);
                            return;
                        }
                        console.log('job created');
                        job.track({}, {
                            error: function(err) {
                                console.log('job error: '+err);
                            },
                            done: function(job) {
                                console.log('job done');
                                job.results({
                                    output_mode: "json_cols"
                                }, function(err, results){
                                    if(err){
                                        console.log(err);
                                        return;
                                    }
                                    console.log(results);
                                    var chart = new splunkjs.UI.Charting.Chart($("#chart-container"), splunkjs.UI.Charting.ChartType.COLUMN, false);
                                    chart.setData(results, {
                                        "chart.stackMode": "stacked"
                                    });
                                    chart.draw();
                                });
                            }
                        });
                    });
                    service.jobs().create('| `cities` | head 10',{
                        status_buckets: 300
                    }, function(err, job){
                        if(err){
                            console.log(err);
                            return;
                        }
                        console.log('job created');
                        job.track({}, {
                            error: function(err) {
                                console.log('job error: '+err);
                            },
                            done: function(job) {
                                console.log('job done');
                                job.results({
                                    output_mode: "json_cols"
                                }, function(err, results){
                                    if(err){
                                        console.log(err);
                                        return;
                                    }
                                    console.log(results);
                                    var chart = new splunkjs.UI.Charting.Chart($("#cities"), splunkjs.UI.Charting.ChartType.COLUMN, false);
                                    chart.setData(results, {
                                        "chart.stackMode": "stacked"
                                    });
                                    chart.draw();

                                });
                            }
                        });
                    });
                });
            });
            
        </script>
</script>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<div id="chart-container"></div>
<div id="cities"></div>

app/views/searches/show.html.erb
<%- model_class = Search -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @search.name %></dd>

  <dt><strong><%= model_class.human_attribute_name(:splunkquery) %>:</strong></dt>
  <dd><%= @search.splunkquery %></dd>

  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @search.user_id %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              searches_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_search_path(@search), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              search_path(@search),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>